language: node_js
node_js: "8"

os: 
  - osx
  - linux

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

osx_image: xcode9.1
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - npm run publish

branches:
  only: 
    - get-deb
