matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "6"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: node_js
      node_js: "7"

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - build-essential
      - libxext-dev
      - libxtst-dev
      - libxkbfile-dev

  artifacts:
    paths:
      - $(ls ./dist/*.AppImage | tr "\n" ":")
      - $(ls ./dist/*.deb | tr "\n" ":")
      - $(ls ./dist/*.snap | tr "\n" ":")
      - $(ls ./dist/*.dmg | tr "\n" ":")
      - $(ls ./dist/*.zip | tr "\n" ":")
      - $(ls ./dist/*.dmg.blockmap | tr "\n" ":")
      - $(ls ./dist/github/*.json | tr "\n" ":")
      - $(ls ./dist/github/*.yml | tr "\n" ":")
      - $(ls ./dist/*.yml | tr "\n" ":")
      - $(ls ./dist/mac/*.yml | tr "\n" ":")
      - $(ls ./dist/linux/*.yml | tr "\n" ":")

before_install:
  - ./scripts/travis-xvfb.sh

cache:
  directories:
    - node_modules
    - app/node_modules
    - ~/.cache

script:
  - npm run travis
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "./node_modules/.bin/electron-builder --x64 --ia32 --win"

        docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:base \
        /bin/bash -c "./node_modules/.bin/electron-builder --x64 --ia32 --linux"
    else
      npm run dist
    fi

  - node ./scripts/prepare-artifacts.js

  # log out /dist files might be useful to know
  # what files are uploaded
  - ls -R dist

notifications:
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
