name: Zulip Desktop CI

on: [push]

jobs:
  windows-build:
    name: Windows Installers
    runs-on: [windows-latest]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12
    - name: Build Release Artifacts
      run: |
        npm install -g windows-build-tools
        npm install
        npm run dist
    - name: Release Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: release-artifacts
        path: dist   
#   tests:
#     name: Zulip Desktop Tests
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#     steps:
#     - uses: actions/checkout@v1
#     - name: Setup Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12
#     - name: Run Tests
#       run: |
#         npm ci
#         npm run test
#       env:
#         CI: true
#     - name: Cache Dependencies
#       id: npm-cache
#       run: |
#         echo "::set-output name=dir::$(npm config get cache)"
#     - uses: actions/cache@v1
#       with:
#         path: ${{ steps.npm-cache.outputs.dir }}
#         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#         restore-keys: |
#           cache-${{ runner.os }}
#     - name: Build Release Artifacts
#       run: |
#         npm install
#         npm run dist
#     - name: Release Artifacts
#       uses: actions/upload-artifact@v1.0.0
#       with:
#         name: release-artifacts
#         path: dist      
